src/instances/HeadcountInstance.ts
Straightforward fix, was more of a warm-up.  Still uncertain about the mappedAfkCheckOption shenanigans going on in the headcount, might look into it.
=> Fixed headcount to say headcount, not afk check

src/commands/punishments/BlacklistMember.ts, src/commands/punishments/MuteMember.ts, src/commands/punishments/SectionSuspendMember.ts, src/commands/punishments/SuspendMember.ts, src/commands/punishments/UnblacklistMember.ts, src/commands/punishments/UnmuteMember.ts, src/commands/punishments/UnsuspendFromSection.ts, src/commands/punishments/UnsuspendMember.ts, src/commands/punishments/WarnMember.ts
Added deferral of replies for all punishment commands to avoid crashing due to timeout.
=> Thompson branch

src/commands/raid-leaders/common/RaidLeaderCommon.ts
Quick fix, not tested against Section with no exalts, but does not impact current behavior.
=> Fixed potential crash if no exaltation dungeons.

src/constants/EmojiConstants.ts, src/instances/RaidInstance.ts
=> Undid reversal of parse and reformatted output.

src/instances/RaidInstance.ts
=> Undid the reversed fields

README.md
=> Updated readme.txt

src/instances/HeadcountInstance.ts, src/instances/RaidInstance.ts
=> Removed random selection of dungeon color for headcount/afk check

package-lock.json, src/definitions/MongoDocumentInterfaces.ts, src/index.ts, src/instances/HeadcountInstance.ts, src/managers/MongoManager.ts, src/managers/PunishmentManager.ts, src/utilities/TimeUtilities.ts
=> Formatting, console.info displays date/time

package-lock.json, src/events/ReadyEvent.ts, src/instances/HeadcountInstance.ts, src/instances/RaidInstance.ts, src/managers/MongoManager.ts, src/managers/QuotaManager.ts, src/utilities/Logger.ts
Fixed two bugs.
- Prevent raiders from sending images or embedding links in feedback channels.
- Quotas will actually reset automatically.
=> Minor fixes

src/commands/moderator/LeaderboardSync.ts, src/commands/staff/Leaderboard.ts, src/utilities/DungeonUtilities.ts
Hotfix for the leaderboard commands.
=> Leaderboard hotfix 1

src/commands/staff/Leaderboard.ts
=> Leaderboard Hotfix 2

src/instances/RaidInstance.ts
adds `@here` to the ping for elite loc - closes #165
small PR per time dman crashes my run - I'll handle rebasing if you want
=> refactor: add here ping for elite loc

package-lock.json, package.json, src/commands/BaseCommand.ts, src/commands/config/ConfigEarlyLocRoles.ts, src/commands/config/common/ConfigCommon.ts, src/commands/owner/SetStatus.ts, src/commands/staff/Clean.ts, src/commands/staff/Leaderboard.ts, src/commands/staff/Yoink.ts, src/utilities/MessageUtilities.ts, src/utilities/MiscUtilities.ts
I honestly thought text in voice would crash the bot but it simply doesn't respond. updating was enough to fix it, so might? fix that one crash that was happening a month ago. unsure if that is even still happening
=> fix: update deps

.github/workflows/compile.yml, .github/workflows/eslint.yml
~~The ESLint workflow doesn't appear to work (it always passes despite not passing). Any idea why this is the case?~~
Added a compile workflow to ensure that code compiles before being pushed to prod.
=> Added compile workflow to ensure code compiles

src/commands/moderator/ForceSync.ts, src/commands/staff/EditName.ts, src/commands/staff/RemoveName.ts
Just a simple PR that fixes some issues with editname and add/remove name.
Essentially, there were some random times where we would get errors due to some members not having a nickname despite me making that assertion. This PR fixes that. It also fixes some other minor issues with said commands.
=> More bug fixes

src/commands/logging/LogKey.ts, src/commands/logging/LogRun.ts, src/commands/raid-leaders/StartAfkCheck.ts, src/commands/raid-leaders/StartHeadcount.ts, src/utilities/DungeonUtilities.ts
if dungeon (or key) is provided in the slash command, skip the dungeon select stuff
=> feat: accept shortcuts

src/commands/logging/LogKey.ts, src/commands/logging/LogRun.ts
Fungal was complaining about how the logging commands were hidden, which interferes with logging chains (presumably, it's so they can track who they've logged).
=> Removed ephemeral from logging

src/managers/VerifyManager.ts
=> Fixed a bug caused by users having a document in db, but no names in it

src/commands/staff/EditName.ts
Remove VRL perms to use "editname" command
=> Remove VRL perms to use 'editname'

src/constants/EmojiConstants.ts, src/managers/QuotaManager.ts
=> Minor improvements

src/commands/BaseCommand.ts, src/commands/staff/Parse.ts
💯 
looks like this:
discuss:
- required option? still support old way?
=> feat(parse): attachment option

src/commands/config/ConfigChannels.ts, src/commands/staff/ManualVerifyMain.ts, src/commands/staff/ManualVerifySection.ts, src/definitions/Types.ts, src/instances/RaidInstance.ts, src/managers/VerifyManager.ts
- Removed excessive verification channel logging options.
- Removed parse button from control panel.
- Control panel now displays raid status properly.
=> Various minor changes.

src/utilities/DJsToProjUtilities.ts
Just removed throwing an error in favor of just logging.
=> refactor(perms): no more error, use error log

src/commands/modmail/Reply.ts, src/events/InteractionEvent.ts, src/managers/ModmailManager.ts
- also: made directions more clear
- also: reply cmd only gives you quota if the message was sent successfully
=> fix(modmail): remove button actually deletes modmail message

src/constants/dungeons/DungeonData.ts, src/constants/dungeons/DungeonModifiers.ts, src/constants/dungeons/MappedAfkCheckReactions.ts
Small PR that adds the Hidden Interregnum dungeon and Syndicate Takeover modification to the bot.
=> feat(dungeons): added hidden interregnum dgn, syndicate takeover mod

src/commands/raid-leaders/StartAfkCheck.ts, src/commands/raid-leaders/StartHeadcount.ts, src/constants/EmojiConstants.ts, src/constants/dungeons/DungeonData.ts, src/constants/dungeons/MappedAfkCheckReactions.ts
=> Added 'Steamworks' and 'Suflurous Wetlands'

src/instances/Common.ts
=> refactor(modifiers): say none listed instead of other modifiers)

src/managers/QuotaManager.ts
=> refactor(quota): ensure member has role and exists

package-lock.json, package.json, src/commands/general/Stats.ts, src/commands/logging/AddQuotaPoints.ts, src/definitions/MongoDocumentInterfaces.ts, src/events/QuotaEvent.ts, src/managers/LoggerManager.ts, src/managers/MongoManager.ts, src/managers/QuotaManager.ts
for now, with the ts-ignore calls, ~~it works *with* the old data (i think, i had to delete it to make it work)~~ (does not)
=> feat: per-server quotapoints

src/managers/QuotaManager.ts
forgot to move this after the types were changed
=> fix(quotapoints): handle negative values properly

src/commands/staff/ParseVcless.ts
=> Fix to /parsevcless

src/constants/dungeons/DungeonData.ts
remove cshield from base dungeons since it's shit now
works in theory but i had to delete an override in order to make it work... so servers might still have to manually remove it
=> fix: cshield

src/events/ReadyEvent.ts
🤡 
Promise.all(action that adds to local array)
Promise.all(action that depends on local array)
Basically, the code was faulty because the promises ran at the same time and the condition always returned false
=> fix: bad logic in dead feedback clearing

src/commands/staff/ParseVcless.ts
=> Removed 'ephemeral' from 'parsevcless' results

src/constants/dungeons/DungeonData.ts, src/constants/dungeons/MappedAfkCheckReactions.ts
Tested it and it seems to work!
=> Added 'Moonlight Village' dungeon and updated some reactions

src/constants/dungeons/DungeonData.ts, src/constants/dungeons/MappedAfkCheckReactions.ts
Added "Advanced Nest" and "Advanced Steamworks" as dungeons. 
Only difference between them and their non-advanced variant is the key and portal colors, aswell as the word "advanced", otherwise its just a copy-paste from the regular ones.
=> Advanced dungeons

src/commands/logging/LogKey.ts
Added "steamworks" to the "key" argument's string choice list in /logkey.
=> Added "steamworks" to /logkey
