src/instances/Common.ts
src/instances/RaidInstance.ts

3 Issues addressed.
1. Return statement added to prevent crashes when raiders rejoin vc
2. Moderators should now have access to control panels.
3. Nitro reacts should only work for users with Nitro***
*** This requires testing with users that DO and DO NOT have Nitro.  I attempted to avoid a hard-coded solution that would be specific to Dungeoneer, but can't test without nitro.

Thompson branch

---

src/commands/raid-leaders/StartAfkCheck.ts
src/commands/raid-leaders/StartHeadcount.ts
src/commands/raid-leaders/common/RaidLeaderCommon.ts
src/instances/Common.ts

Refactored steps 1-3 in both StartHeadcount and StartAfkCheck into methods in Common.ts
Minor change: added specific dropdown for Exaltation Dungeons.
I recommend viewing changes in split mode rather than unified.

Refactored Headcount/Afkcheck using common methods

---

package.json
src/commands/raid-leaders/StartAfkCheck.ts
src/commands/raid-leaders/common/RaidLeaderCommon.ts
src/index.ts
src/instances/Common.ts
src/instances/HeadcountInstance.ts

A few minor bug fixes.
- Fixed a bug where `universalEarlyLocReactions` might not exist (leading to errors since we're accessing an undefined object)
- Selecting a VC for an afk check in a different channel than the control panel channel would result in interaction failed
Also made error logging more detailed for some cases.

Minor fixes

---

src/commands/config/ConfigAfkCheck.ts
src/definitions/DungeonRaidInterfaces.ts
src/instances/RaidInstance.ts
src/managers/MongoManager.ts

- adds a `defaultPosition` to AFK check config, allowing staff to configure default voice channel position for the raid channel. closes #59
- input could be handled better and check if a user inputs a channel (then adding 1 to the position) though.

feat(config): add defaultPosition in AFK check config

---

src/commands/raid-leaders/StartAfkCheck.ts
src/instances/HeadcountInstance.ts
src/instances/RaidInstance.ts

- AFK check relies on current time - instead of using the voice channel's creation time. closes #139
- fun workaround, starting a new AFK check using the slash command checks for any ActiveHeadcounts with the same user id and silently converts instead of creating an AFK check. closes #137
- adds a new enum to show users that the headcount is converting, improving ux. closes #151
small PR per time dman crashes my run - I'll handle rebasing if you want

refactor(headcount): change converting to afk check

---

src/instances/HeadcountInstance.ts

headcounts always have interested button + key react buttons
so when receiving a call to addKeyReact, check if we have someone in each of the categories and the length isn't 0, then compare to the original size -1 for the interested button for headcounts that have multiple reacts

feat: ping rls when all keys have a react

---

.eslintrc.json
src/instances/Common.ts
src/instances/RaidInstance.ts
src/managers/QuotaManager.ts

Possibly fixed issue #131: Specifically, the issue was that the bot encountered an `AbortError: The user aborted a request.` error when trying to edit the quota leaderboard embed. Because the `run` function (responsible for periodically updating the quota leaderboards) needs to be called again after running, an error like the one I just said will prevent said function from calling itself, resulting in what appears to be quotas hanging. 
Fixed issue #149.
Fixed issue #180.
Acknowledged, but did not add, #115: I don't really think it's worthwhile to add an unreact feature. I added a warning -- in bold -- that clearly states that you won't be able to unreact. If someone really needs to leave, they can just message a leader.
Removed the style rule `linebreak-style` since I don't think it's …

More fixes

---

src/Bot.ts
src/commands/config/ConfigAfkCheck.ts
src/events/ErrorEvent.ts
src/events/InteractionEvent.ts
src/events/RatelimitEvent.ts
src/events/index.ts
src/instances/HeadcountInstance.ts
src/instances/RaidInstance.ts
src/managers/PunishmentManager.ts
src/managers/QuotaManager.ts
src/managers/VerifyManager.ts
src/utilities/collectors/AdvancedCollector.ts
src/utilities/fetch-get-request/GlobalFgrUtilities.ts
src/utilities/fetch-get-request/GuildFgrUtilities.ts

Creates a logger in most files that can throw an error and logs it. This __will__ spam the shit out of logs, but it will be very useful for finding the reason for bugs (i.e. crashes, headcounts randomly not working, unexpected behavior.)
#
Previous code simply catches errors and doesn't allow for the `errorEvent` or any internal node events to log info about the error that was caught.
```js
try {...}
catch (e) {
return;
}
```
Thus, the PR proposes changing simply *catching and returning* to logging pretty much everything that can return an error, most situations like this:
```js
try {...}
catch (e) {
LOGGER.error(e);
return;
}
```
or this:
```js
.catch(LOGGER.error)
```
#
This also implements a simple debug log for the `ratelimitEvent` passed by discord.js for anything that the bot may …

refactor(logging): adding tons of logging for errors and rate-limits

---

package.json
src/commands/config/ConfigChannels.ts
src/commands/config/ConfigRoles.ts
src/commands/staff/EditName.ts
src/commands/staff/ManualVerifyMain.ts
src/commands/staff/ManualVerifySection.ts
src/commands/staff/RemoveName.ts
src/managers/UserManager.ts
src/managers/VerifyManager.ts
src/private-api/PrivateApiDefinitions.ts
src/utilities/MiscUtilities.ts

This PR fixes a few bugs for verification found during the initial testing period, along with a few other bugs elsewhere.
- Possibly fixed a bug where the bot would change the nickname or add the role, and then somehow immediately undo that operation (this is most likely caused by a rate limiting issue on Discord's side).
- The bot will no longer ping moderators in any verification logging messages (e.g., you won't get a ping when you manually verify someone).
- Verification log messages are more consistent.
- Fixed a bug where members with the same username as their desired in-game name won't get a nickname change. 
- What should happen is, if a member has the same username as the desired IGN, a dot will be appended to their name. 
- What actually happens is that the bot doesn't change …

[1.2.1] Verification hotfix.

---

src/commands/config/ConfigVerification.ts
src/commands/staff/CheckManualVerifyApp.ts
src/commands/staff/EditName.ts
src/commands/staff/Find.ts
src/commands/staff/ManualVerifyMain.ts
src/commands/staff/RemoveName.ts
src/definitions/MongoDocumentInterfaces.ts
src/definitions/VerificationInterfaces.ts
src/events/InteractionEvent.ts
src/index.ts
src/managers/MongoManager.ts
src/managers/VerifyManager.ts
src/utilities/Logger.ts

This PR adds the ability for verification to be done 100% manually. To be explicit, rather than having the bot automatically verify members by checking their RealmEye profile, staff members now have the ability to configure the bot so the bot asks the user for a screenshot (perhaps, of them in their vault saying their Discord tag); once the bot gets the screenshot, this screenshot will be sent to the manual verification channel, where a staff member can look at it.

feat(verif): forced manual verification added

---

src/commands/config/ConfigDungeons.ts
src/constants/dungeons/DungeonData.ts
src/definitions/DungeonRaidInterfaces.ts
src/instances/RaidInstance.ts

~~location is now required before starting the raid~~
added config option to require location per dungeon, oryx 3 defaults to true (since it's the only one that cannot ever proceed in a bazaar)
closes #220

refactor(afk-check): require location before start

---

src/private-api/PrivateApiDefinitions.ts

RealmEye recently removed CQC and experience from player and guild profiles. I updated the [API](https://github.com/ToogaInc/RealmEyeSharper/pull/10) to account for this, but also need to update it here on the bot.

feat(api): removed properties that the realmeye api no longer returns

---

src/Bot.ts
src/commands/general/Stats.ts
src/commands/index.ts
src/commands/logging/AddQuotaPoints.ts
src/definitions/MongoDocumentInterfaces.ts
src/managers/LoggerManager.ts
src/managers/MongoManager.ts
src/managers/QuotaManager.ts

Support for QuotaPoints, for purposes of a leader shop system.
- Each UserDoc tracks a user's quota points in details.quotaPoints
- When quota is logged by any means, the points are automatically added to the user's quotaPoints
- AddQuotaPoints command for use by HRL, Officer, Mod can add positive or negative points
- Stats shows user's quota points

Support for QuotaPoints

---

src/events/InteractionEvent.ts

Before, users that ran a command (that limited the number of active users) that threw an error would not be allowed to run that command again until the bot is restarted (they would get an "Already Using Command" error from the bot). 
This PR should fix that issue.

fix: cmds that errored no longer locks user out

---

package.json
src/commands/config/ConfigDungeons.ts
src/definitions/DungeonRaidInterfaces.ts
src/instances/RaidInstance.ts

Fixes two bugs:
- Custom dungeons should now work with AFK checks
- Custom dungeons should now work in quotas
@Deaththth

fix: custom dungeons could not be added to quota/afk

---

src/events/ReadyEvent.ts
src/instances/RaidInstance.ts

auto deletes feedbacks without an active raid vc on start only
dropped feedback time to 5 minutes to stop it from happening overall (its probably just a restart/crash in the 10 min time)
relies on the uuid in the feedback channel topic

fix: dead feedbacks are deleted on start

---

src/instances/RaidInstance.ts

- Easy access to look back on raid logs and know which afk check it corresponded to (the thread starts on the control panel message)
- The thread does not get deleted, instead it is archived, meaning that people can open it and continue to talk if necessary (There is no limit on archived threads)
- The thread automatically closes after 1 day (the next lowest is 1 hour so whatever)
- Threads are opt-in, you have to go into the thread to get annoyed by new message notifications
Click the channel name in the top-right to make it full screen (directed to securities)

feat: raid-logs are stored in threads

---

package-lock.json
package.json
src/commands/config/ConfigChannels.ts
src/commands/config/ConfigRoles.ts
src/managers/ModmailManager.ts
src/managers/MongoManager.ts

discord.js v13.8.0 was deprecated. As noted in the Discord.js announcement:
So, this PR should also fix the issues we've been having with various dropdowns not working either.
---
One thing to note: I've added a cast to `never` (e.g., `"" as never`) when updating values in the database. This is because the possible properties that TypeScript sees can be one of many different value types, and I guess TypeScript really wants us to assert that the value that we're using to update the entry in the database satisfies all of those types? Not too sure, though.

chore: bump discord.js version to v13.14.0

---

src/commands/logging/LogRun.ts
src/commands/raid-leaders/StartAfkCheck.ts
src/commands/raid-leaders/StartHeadcount.ts
src/constants/EmojiConstants.ts
src/constants/GeneralConstants.ts
src/constants/dungeons/DungeonData.ts
src/constants/dungeons/MappedAfkCheckReactions.ts
src/definitions/Types.ts

- Added Realm Clearing and Exalt Dungeon as options for headcount/afkcheck
- Added the Speedy reaction emoji (for realm clearing HC)
- Updated the "dungeon" option shortcut for the logrun, headcount and afkcheck commands. Now includes ALL exalt dungeons and 'Misc' for miscellaneous dungeons.

feat(dungeon): add realm clearing, misc, exalt options

---

src/commands/config/ConfigChannels.ts
src/commands/config/ConfigDungeons.ts
src/definitions/DungeonRaidInterfaces.ts
src/definitions/MongoDocumentInterfaces.ts
src/events/InteractionEvent.ts
src/events/MessageDeleteEvent.ts
src/instances/HeadcountInstance.ts
src/instances/RaidInstance.ts
src/managers/MongoManager.ts

- Override a base dungeon and select a role by mentioning it or posting the role ID after clicking the mention roles button
- Start a headcount or afk check, the roles will be automatically mentioned on the first message. This means that the pre-AFK message will mention users
Closes #68

feat: role pings for dungeons and afk-checks

---

src/constants/dungeons/DungeonData.ts
src/constants/dungeons/MappedAfkCheckReactions.ts

Made it so that the HC/AFK for advanced nest will only show the green bee, which is specific to advanced nest. This is to help show the raiders that it is advanced and not a normal nest, although the name is also already different. 
Sorry for the extra PR, i wanted to add this to the first one, but realmeye didnt have the picture of green bee, so I assumed no one did, but apparently its in a deca blog.

Advanced Nest icon

---

src/commands/logging/LogKey.ts
src/constants/GeneralConstants.ts
src/constants/dungeons/DungeonData.ts
src/constants/dungeons/MappedAfkCheckReactions.ts
src/managers/LoggerManager.ts

- Added Spectral Penitentiary to DungeonData as exalt dungeon
- Added Spectral Penitentiary to DungeonData as a react for Exalt Dungeon headcount
- Added Spectral Penitentiary to DUNGEON_SHORTCUTS
- Added Spectral Penitentiary to LogKey ("SPECTRAL_KEY")
- Added Spectral Penitentiary to LoggerManager
- Added Spectral Penitentiary to MappedAfkCheckReactions

add Spectral Penitentiary

---

src/index.ts
src/instances/RaidInstance.ts

Custom Dungeons with a set vc limit were not correctly overriding the default sections vc limit. Base dungeons with set vc limits already does override the section vc limit as intended.

custom dungeon vc limit overrides default section vc limit

---

src/commands/logging/LogKey.ts
src/constants/GeneralConstants.ts
src/constants/dungeons/DungeonData.ts
src/constants/dungeons/MappedAfkCheckReactions.ts
src/managers/LoggerManager.ts

- Added Ice Citadel to DungeonData as exalt dungeon
- Added Ice Citadel to DungeonData as a react for Exalt Dungeon headcount
- Added Ice Citadel to DUNGEON_SHORTCUTS
- Added Ice Citadel to LogKey ("CITADEL_KEY")
- Added Ice Citadel to LoggerManager
- Added Ice Citadel to MappedAfkCheckReactions
Similar to #294

add Ice Citadel
